course=["data analytics","ds","mern","fullstack"]
fees=[10000,20000,40000,50000,60000]
print(course,fees)
print(type(course))
print(type(fees))
print(len(course))
print(len(fees))
print("ds" in course)
print("ss" not in fees)
print(fees[1])
print(fees[1:6])
print(fees[1:])
print(fees[:6])
print(fees[-1])
print(fees[-6:-4])
print(fees[-6:])
print(fees[:-3])
course[1]="datascience"
print(course)
course.append("java")
print(course)
course.insert(0,"softwaretesting")
print(course)
course.extend(fees)
print(course)
course.remove("softwaretesting")
print(course)
course.pop(4)
print(course)
course.pop()
print(course)
del course[2]
print(course)
'''course.clear()
print(course)
del course
print(course)'''
for i in course:
    print(i)
course.pop()
course.pop()
course.pop()
course.pop()
print(course)   
course.sort()
print(course)
course.sort(reverse=True)
print(course)
x=course.copy()
print(x)
y=list(course) 
print(y)
print(x+y)
x.extend(y)
print(x)
print(x.count("fullstack"))