import os

#task 1
# a=open("taskfile.txt","x")
# a=open("taskfile.txt","w")
# a.write("arya is a girl")
# a.close()
# a=open("taskfile.txt","a")
# a.write("\nshe is studying in 5std\nat bharathiya vidhya bavan english school")
# a.close()
# a=open("taskfile.txt","r")
# print(a.read())
# a.close()
# a=open("taskfile.txt","r")
# print(a.readline())
# a.close()
# a=open("taskfile.txt","r")
# print(a.read(20))
# a.close()
# os.remove("taskfile.txt")

#task 2
# x=open("file1.txt","x")
# x=open("file1.txt","w")
# x.write("Hai,welcome to futuralabs")
# x.close()
# x=open("file1.txt","r")
# print(x.read())
# x.close()
# y=open("file2.txt","x")
# x=open("file1.txt","r")
# y=open("file2.txt","w")
# for i in x:
#     y.write(i)
#     print(i)
# x.close()
# y.close()
# os.remove("file1.txt")
# os.remove("file2.txt")

# #task 3
# # x=open("file1.txt","x")
# x=open("file1.txt","w")
# x.write("python is a programming language ")
# x.close()
# x=open("file1.txt","r")
# print(x.read())
# x.close()
# # y=open("file2.txt","x")
# y=open("file2.txt","w")
# y.write("it has simple syntax ")
# y.close()
# y=open("file2.txt","r")
# print(y.read())
# y.close()
# # z=open("file3.txt","x")
# x=open("file1.txt","r")
# y=open("file2.txt","r")
# z=open("file3.txt","w")
# for i in x:
#     z.write(i)
#     for j in y:
#         z.write(i)
#         print(i,j)
# x.close()
# y.close()
# z.close()
# os.remove("file1.txt")
# os.remove("file2.txt")
# os.remove("file3.txt")