x=(1,2,3,4,5,6,7,"xyz","qqq","rrr")
print(x)
print(type(x))
print(len(x))
print(x[1])
print(x[1:8])
print(x[:8])
print(x[1:])
print(x[-1])
print(x[-8:-1])
print(x[-8:])
print(x[:-1])
print(1 in x)
print("1" not in x)
y=list(x)
print(y)
y.append(8)
print(y)
y.insert(0,"0ne")
print(y)
z=[1,1,2,2,3,4]
y.extend(z)
x=tuple(y)
print(x)
#count andindex in tuples
t=(1,2,2,3,4,5,6,7,6,6,66)
print(len(t))
c=t.count(6)
print(c)
i=t.index(6)
print(i)
#packing
f=("apple","pineappple","cherry")
#UNPACKING
(red,yellow,cherryred)=f
print(red)
print(yellow)
print(cherryred)
for i in f:
    print(i)
    